import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/Footer";

const roboto = Roboto({
  subsets: ["vietnamese"],
});

const roboto_mono = Roboto_Mono({
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased bg-gray-50 relative`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
